<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CryptoFotos</RootNamespace>
    <Nullable>enable</Nullable>
    <ApplicationIcon>crypt.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="login.txt" />
  </ItemGroup>
</Project>
