namespace CryptoFotos.Security
{
    // <auto-generated>
    // Gerado durante o build para armazenar a chave publica RSA de integridade.
    // Em desenvolvimento (Debug), constantes vazias desativam a verificacao de assinatura
    // e o IntegrityGuard usa auto-pin de hash local (AppData).
    internal static class IntegrityToken
    {
        public const string ModulusBase64 = "";
        public const string ExponentBase64 = "";

        public static bool HasToken => ModulusBase64.Length > 0 && ExponentBase64.Length > 0;
    }
}
